name: CD workflow

on:
  release:
    types: published

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Deploy
      run: |
       echo "Deploying release ${{ github.event.release.tag_name }}"
       curl ${{ secrets.RENDER_DEPLOY_HOOK }}
